channels:
  - conda-forge
  - anaconda
  - bioconda
dependencies:
  - python=3.10.11
  - pandas=2.0.1
  - numpy=1.23.5
  - pyaml=23.7.0
  - bcftools=1.17
  - pytabix=0.1
  - pip=23.2.1
  - pip:
    - tensorflow==2.11
    - open-cravat==2.2.9
