channels:
  - conda-forge
  - anaconda
  - bioconda
dependencies:
<<<<<<< HEAD:configs/envs/ditto-nf.yaml
  - python=3.10.8
  - pandas=1.5.2
  - numpy=1.23.5
  - pyaml=23.7.0
  - bcftools=1.2
  - pip=23.2.1
  - pip:
    - tensorflow==2.11
    - pytabix==0.1
    - open-cravat==2.4.1
=======
  - pyaml=23.7.0
  - pytabix=0.1
  - open-cravat=2.4.1
>>>>>>> 36232d9840785aba79f64443a102c079beea6049:configs/envs/open-cravat.yaml
