name: testing

channels:
  - conda-forge
  - anaconda
  - bioconda

dependencies:
  - python=3.9.7
  - pandas=1.3.3
  - numpy=1.19.5
  - scikit-learn=0.24.2
  - imbalanced-learn=0.7.0
  - scipy=1.7.1
  - shap=0.39.0
<<<<<<< HEAD
  - bcftools==1.13
=======
  - bcftools=1.13
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
  - pip=21.2.4
  - bioconda::snakefmt==0.4.0
  - bioconda::snakemake==6.0.5
  - seaborn=0.11.2
<<<<<<< HEAD
  - gpy
  - pip:
    - lz4==3.1.3
    - pyEntrezId==1.5.8.2
    - black==20.8b1
=======
  - black=20.8b1
  - pylint=2.11.1
  - lz4=3.1.3
  - gpy=1.10.0
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
