# columns to be needed in dataset
columns:
    - AAChange.refGene
    - ID
    #- AF_ESP
    #- AF_EXAC
    #- AF_TGP
    - CLNREVSTAT
    - CLNSIG
    - CLNVC
    - MC
    - Func.refGene
    - ExonicFunc.refGene
    - SIFT_score
    - Polyphen2_HDIV_score
    - Polyphen2_HVAR_score
    - LRT_score
    - MutationTaster_score
    - MutationAssessor_score
    - FATHMM_score
    - PROVEAN_score
    - VEST3_score
    - MetaSVM_score
    - MetaLR_score
    - M-CAP_score
    - CADD_phred
    - DANN_score
    - fathmm-MKL_coding_score
    - Eigen_coding_or_noncoding
    - Eigen-PC-raw
    - GenoCanyon_score
    - integrated_fitCons_score
    - GERP++_RS
    - phyloP100way_vertebrate
    - phyloP20way_mammalian
    - phastCons100way_vertebrate
    - phastCons20way_mammalian
    - SiPhy_29way_logOdds
    - dbscSNV_ADA_SCORE
    - dbscSNV_RF_SCORE
    - AF_1
    - AF_popmax
    - AF_male
    - AF_female
    - AF_raw
    - AF_afr
    - AF_amr
    - AF_eas
    - AF_nfe
    - AF_fin
    - AF_asj
    - AF_oth
    - non_topmed_AF_popmax
    - non_neuro_AF_popmax
    - controls_AF_popmax
    - MCAP13
    - REVEL
    - gerp++gt2
    - CADD13_PHRED
    - is_snp
    - InterVar_automated
    - PVS1
    - PS1
    - PS2
    - PS3
    - PS4
    - PM1
    - PM2
    - PM3
    - PM4
    - PM5
    - PM6
    - PP1
    - PP2
    - PP3
    - PP4
    - PP5
    - BA1
    - BS1
    - BS2
    - BS3
    - BS4
    - BP1
    - BP2
    - BP3
    - BP4
    - BP5
    - BP6
    - BP7

ClinicalSignificance:
    2-class:
      - Benign
      - Pathogenic
    3-class:
      - Benign
      - Uncertain_significance
      - Pathogenic
    4-class:
      - Benign
      - Benign/Likely_benign
      - Pathogenic/Likely_pathogenic
      - Pathogenic
    5-class:
      - Benign
      - Uncertain_significance
      - Pathogenic
      - Likely_pathogenic
      - Likely_benign
    6-class:
      - Benign
      - Benign/Likely_benign
      - Pathogenic/Likely_pathogenic
      - Pathogenic
      - Likely_pathogenic
      - Likely_benign
    optional:
      - not provided
      - Benign/Likely_benign
      - Pathogenic/Likely_pathogenic
      - Conflicting interpretations of pathogenicity
      - drug response
      - association
      - risk factor
      - protective
      - Affects
      - conflicting data from submitters
      - other
      - no interpretation for the single variant  # concerns compound hets
      - "-"
      - association not found   # not certain what this exactly refers to. Need to investigate

Fill_NAs:
 - SIFT_score
 - Polyphen2_HDIV_score
 - Polyphen2_HVAR_score
 - LRT_score
 - MutationTaster_score
 - MutationAssessor_score
 - FATHMM_score
 - PROVEAN_score
 - VEST3_score
 - MetaSVM_score
 - MetaLR_score
 - M-CAP_score
 - CADD_phred
 - DANN_score
 - fathmm-MKL_coding_score
 - Eigen-PC-raw
 - GenoCanyon_score
 - integrated_fitCons_score
 - GERP++_RS
 - phyloP100way_vertebrate
 - phyloP20way_mammalian
 - phastCons100way_vertebrate
 - phastCons20way_mammalian
 - SiPhy_29way_logOdds
 - dbscSNV_ADA_SCORE
 - dbscSNV_RF_SCORE
 - AF_1
 - AF_popmax
 - AF_male
 - AF_female
 - AF_raw
 - AF_afr
 - AF_amr
 - AF_eas
 - AF_nfe
 - AF_fin
 - AF_asj
 - AF_oth
 - non_topmed_AF_popmax
 - non_neuro_AF_popmax
 - controls_AF_popmax
 - MCAP13
 - REVEL
 - gerp++gt2
 - CADD13_PHRED
 - is_snp
 - PVS1
 - PS1
 - PS2
 - PS3
 - PS4
 - PM1
 - PM2
 - PM3
 - PM4
 - PM5
 - PM6
 - PP1
 - PP2
 - PP3
 - PP4
 - PP5
 - BA1
 - BS1
 - BS2
 - BS3
 - BS4
 - BP1
 - BP2
 - BP3
 - BP4
 - BP5
 - BP6
 - BP7
 - CLNREVSTAT_criteria_provided
 - CLNREVSTAT_no_assertion_criteria_provided
 - CLNREVSTAT_practice_guideline
 - CLNREVSTAT_reviewed_by_expert_panel
 - Func.refGene_UTR3
 - Func.refGene_UTR5
 - Func.refGene_UTR5\x3bUTR3
 - Func.refGene_downstream
 - Func.refGene_exonic
 - Func.refGene_exonic\x3bsplicing
 - Func.refGene_intergenic
 - Func.refGene_intronic
 - Func.refGene_ncRNA_UTR5
 - Func.refGene_ncRNA_exonic
 - Func.refGene_ncRNA_exonic\x3bsplicing
 - Func.refGene_ncRNA_intronic
 - Func.refGene_ncRNA_splicing
 - Func.refGene_splicing
 - Func.refGene_upstream
 - Func.refGene_upstream\x3bdownstream
 - ExonicFunc.refGene_frameshift_deletion
 - ExonicFunc.refGene_frameshift_insertion
 - ExonicFunc.refGene_frameshift_substitution
 - ExonicFunc.refGene_nonframeshift_deletion
 - ExonicFunc.refGene_nonframeshift_insertion
 - ExonicFunc.refGene_nonframeshift_substitution
 - ExonicFunc.refGene_nonsynonymous_SNV
 - ExonicFunc.refGene_stopgain
 - ExonicFunc.refGene_stoploss
 - ExonicFunc.refGene_synonymous_SNV
 - ExonicFunc.refGene_unknown
 - Eigen_coding_or_noncoding_c
 - Eigen_coding_or_noncoding_n
 - InterVar_automated_Benign
 - InterVar_automated_Likely_benign
 - InterVar_automated_Likely_pathogenic
 - InterVar_automated_Pathogenic
 - InterVar_automated_Uncertain_significance

Fill_1_NAs:
  SIFT_score:
    0.5
  Polyphen2_HDIV_score:
    0.5
  Polyphen2_HVAR_score:
    0.5
  LRT_score:
    0.5     #The score ranges from 0 to 1 and a larger score signifies that the codon is more constrained or a NS is more likely to be deleterious.
  MutationTaster_score:
    0.5
  MutationAssessor_score:
    0   #MutationAssessor functional impact combined score (MAori). The score ranges from -5.135 to 6.49 in dbNSFP.
  FATHMM_score:
    -3.5         #weighted for human inherited- disease mutations with Disease Ontology (FATHMMori). Scores range from -18.09 to 11.0. This is for coding and MKL for non-coding variants
  PROVEAN_score:
    0           # range - -14 to 13.57
  VEST3_score:
    0.5           # range - 0 to 1
  MetaSVM_score:
    0.5         # range - -2 to 3
  MetaLR_score:
    0.5          # range - 0 to 1
  M-CAP_score:
    0.5           # range - 0 to 1
  CADD_phred:
    20
  DANN_score:
    0.5            # range - 0 to 1. deep neural network (DNN) to recognize pathogenic variants
  fathmm-MKL_coding_score:
    0.5 # range - 0 to 1. This is for non-coding variants - functional prediction tool
  Eigen-PC-raw:
    -20          #functional annotations. input range - -3.252 to 8.426.
  GenoCanyon_score:
    0.5      # range - 0 to 1
  integrated_fitCons_score:
    0.5 # range - 0 to 1
  GERP++_RS:
    -20
  phyloP100way_vertebrate:
    20
  phyloP20way_mammalian:
    20
  phastCons100way_vertebrate:
    0.5
  phastCons20way_mammalian:
    0.5
  SiPhy_29way_logOdds:
    15    # input range - 0 to 33.272. SiPhy score based on 29 mammals genomes. The larger the score, the more conserved the site.
  dbscSNV_ADA_SCORE:
    0
  dbscSNV_RF_SCORE:
    0
  AF_1:
    0.05
  AF_popmax:
    0.05
  AF_male:
    0.05
  AF_female:
    0.05
  AF_raw:
    0.05
  AF_afr:
    0.05
  AF_amr:
    0.05
  AF_eas:
    0.05
  AF_nfe:
    0.05
  AF_fin:
    0.05
  AF_asj:
    0.05
  AF_oth:
    0.05
  non_topmed_AF_popmax:
    0.05
  non_neuro_AF_popmax:
    0.05
  controls_AF_popmax:
    0.05
  MCAP13:
    0.5
  REVEL:
    0.5             # predicting the pathogenicity of missense variants. It integrates scores from MutPred, FATHMM v2.3, VEST 3.0, PolyPhen-2, SIFT, PROVEAN, MutationAssessor, MutationTaster, LRT, GERP++, SiPhy, phyloP, and phastCons. Score range from 0 to 1 and variants with higher scores are predicted to be more likely to be pathogenic.
  gerp++gt2:
    -20
  CADD13_PHRED:
    20
  is_snp:
    0
  PVS1:
    0
  PS1:
    0
  PS2:
    0
  PS3:
    0
  PS4:
    0
  PM1:
    0
  PM2:
    0
  PM3:
    0
  PM4:
    0
  PM5:
    0
  PM6:
    0
  PP1:
    0
  PP2:
    0
  PP3:
    0
  PP4:
    0
  PP5:
    0
  BA1:
    0
  BS1:
    0
  BS2:
    0
  BS3:
    0
  BS4:
    0
  BP1:
    0
  BP2:
    0
  BP3:
    0
  BP4:
    0
  BP5:
    0
  BP6:
    0
  BP7:
    0
  CLNREVSTAT_criteria_provided:
    0
  CLNREVSTAT_no_assertion_criteria_provided:
    0
  CLNREVSTAT_practice_guideline:
    0
  CLNREVSTAT_reviewed_by_expert_panel:
    0
  Func.refGene_UTR3:
    0
  Func.refGene_UTR5:
    0
  Func.refGene_UTR5\x3bUTR3:
    0
  Func.refGene_downstream:
    0
  Func.refGene_exonic:
    0
  Func.refGene_exonic\x3bsplicing:
    0
  Func.refGene_intergenic:
    0
  Func.refGene_intronic:
    0
  Func.refGene_ncRNA_exonic:
    0
  Func.refGene_ncRNA_exonic\x3bsplicing:
    0
  Func.refGene_ncRNA_intronic:
    0
  Func.refGene_ncRNA_splicing:
    0
  Func.refGene_splicing:
    0
  Func.refGene_upstream:
    0
  Func.refGene_upstream\x3bdownstream:
    0
  ExonicFunc.refGene_frameshift_deletion:
    0
  ExonicFunc.refGene_frameshift_insertion:
    0
  ExonicFunc.refGene_frameshift_substitution:
    0
  ExonicFunc.refGene_nonframeshift_deletion:
    0
  ExonicFunc.refGene_nonframeshift_insertion:
    0
  ExonicFunc.refGene_nonframeshift_substitution:
    0
  ExonicFunc.refGene_nonsynonymous_SNV:
    0
  ExonicFunc.refGene_stopgain:
    0
  ExonicFunc.refGene_stoploss:
    0
  ExonicFunc.refGene_synonymous_SNV:
    0
  ExonicFunc.refGene_unknown:
    0
  Eigen_coding_or_noncoding_c:
    0
  Eigen_coding_or_noncoding_n:
    0
  InterVar_automated_Benign:
    0
  InterVar_automated_Likely_benign:
    0
  InterVar_automated_Likely_pathogenic:
    0
  InterVar_automated_Pathogenic:
    0
  InterVar_automated_Uncertain_significance:
    0
