# columns to be needed in dataset
columns:
 - '#chr'
 - pos(1-based)
 - ref
 - alt
 - aaref
 - aaalt
 - genename
 - Ensembl_geneid
 - Ensembl_transcriptid
 - Ensembl_proteinid
 - Uniprot_acc
 - cds_strand
 - SIFT_score
 - SIFT4G_score
 - Polyphen2_HDIV_score
 - Polyphen2_HVAR_score
 - LRT_score
 - LRT_Omega
 - MutationTaster_converted_rankscore
 - MutationAssessor_score
 - FATHMM_score
 - PROVEAN_score
 - PROVEAN_converted_rankscore
 - VEST4_score
 - MetaSVM_score
 - MetaLR_score
 - Reliability_index
 - MetaRNN_score
 - M-CAP_score
 - REVEL_score
 - MutPred_score
 - MVP_score
 - MPC_score
 - PrimateAI_score
 - DEOGEN2_score
 - BayesDel_addAF_score
 - BayesDel_noAF_score
 - ClinPred_score
 - LIST-S2_score
 - CADD_raw
 - CADD_phred
 - DANN_score
 - fathmm-MKL_coding_score
 - fathmm-XF_coding_score
 - Eigen-raw_coding
 - Eigen-phred_coding
 - Eigen-PC-raw_coding
 - Eigen-PC-phred_coding
 - GenoCanyon_score
 - integrated_fitCons_score
 - integrated_confidence_value
 - GM12878_fitCons_score
 - H1-hESC_fitCons_score
 - HUVEC_fitCons_score
 - LINSIGHT
 - GERP++_NR
 - GERP++_RS
 - phyloP100way_vertebrate
 - phyloP30way_mammalian
 - phyloP17way_primate
 - phastCons100way_vertebrate
 - phastCons30way_mammalian
 - phastCons17way_primate
 - SiPhy_29way_logOdds
 - bStatistic
 - gnomAD_genomes_AF
 - gnomAD_genomes_AFR_AF
 - gnomAD_genomes_AMI_AF
 - gnomAD_genomes_AMR_AF
 - gnomAD_genomes_ASJ_AF
 - gnomAD_genomes_EAS_AF
 - gnomAD_genomes_FIN_AF
 - gnomAD_genomes_MID_AF
 - gnomAD_genomes_NFE_AF
 - gnomAD_genomes_SAS_AF
 - clinvar_clnsig
 - clinvar_review
 - Interpro_domain

ClinicalSignificance:
 - Uncertain_significance
 - Pathogenic
 - Likely_pathogenic
 - Benign
 - Likely_benign
 - Benign/Likely_benign
 - Pathogenic/Likely_pathogenic

BenchmarkSignificance:
 - Pathogenic
 - Likely_pathogenic
 - Likely_benign
 - Benign
 - Benign/Likely_benign
 - Pathogenic/Likely_pathogenic
 - Pathogenic,_other
 - Pathogenic/Likely_pathogenic,_other
 - Pathogenic,_drug_response

Clinsig_train:
  -  Benign
  -  Pathogenic
  -  Likely_benign

Clinsig_test:
  -  Pathogenic/Likely_pathogenic
  -  Likely_pathogenic
  -  Benign/Likely_benign


CLNREVSTAT: #https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/
  -  practice_guideline
  -  reviewed_by_expert_panel
  -  criteria_provided,_multiple_submitters,_no_conflicts
  -  criteria_provided,_single_submitter

var:
    -   '#chr'
    -   pos(1-based)
    -   ref
    -   alt
    -   cds_strand
    -   genename
    -   Ensembl_geneid
    -   Ensembl_transcriptid
    -   Ensembl_proteinid
    -   Uniprot_acc
    -   clinvar_clnsig
    -   clinvar_review
    -   Interpro_domain

allele_freq_columns:
 - gnomAD_genomes_AF
 - gnomAD_genomes_AFR_AF
 - gnomAD_genomes_AMI_AF
 - gnomAD_genomes_AMR_AF
 - gnomAD_genomes_ASJ_AF
 - gnomAD_genomes_EAS_AF
 - gnomAD_genomes_FIN_AF
 - gnomAD_genomes_MID_AF
 - gnomAD_genomes_NFE_AF
 - gnomAD_genomes_SAS_AF

nssnv_columns:
  - '#chr'
	-	pos(1-based)
	-	ref
	-	alt
	-	cds_strand
	-	genename
	-	Ensembl_geneid
	-	Ensembl_transcriptid
	-	Ensembl_proteinid
	-	Uniprot_acc
	-	clinvar_clnsig
	-	clinvar_review
	-	Interpro_domain
	-	SIFT_score
	-	SIFT4G_score
	-	Polyphen2_HDIV_score
	-	Polyphen2_HVAR_score
	-	LRT_score
	-	LRT_Omega
	-	MutationTaster_converted_rankscore
	-	MutationAssessor_score
	-	FATHMM_score
	-	PROVEAN_score
	-	PROVEAN_converted_rankscore
	-	VEST4_score
	-	MetaSVM_score
	-	MetaLR_score
	-	Reliability_index
	-	MetaRNN_score
	-	M-CAP_score
	-	REVEL_score
	-	MutPred_score
	-	MVP_score
	-	MPC_score
	-	PrimateAI_score
	-	DEOGEN2_score
	-	BayesDel_addAF_score
	-	BayesDel_noAF_score
	-	ClinPred_score
	-	LIST-S2_score
	-	CADD_raw
	-	CADD_phred
	-	DANN_score
	-	fathmm-MKL_coding_score
	-	fathmm-XF_coding_score
	-	Eigen-raw_coding
	-	Eigen-phred_coding
	-	Eigen-PC-raw_coding
	-	Eigen-PC-phred_coding
	-	GenoCanyon_score
	-	integrated_fitCons_score
	-	integrated_confidence_value
	-	GM12878_fitCons_score
	-	H1-hESC_fitCons_score
	-	HUVEC_fitCons_score
	-	LINSIGHT
	-	GERP++_NR
	-	GERP++_RS
	-	phyloP100way_vertebrate
	-	phyloP30way_mammalian
	-	phyloP17way_primate
	-	phastCons100way_vertebrate
	-	phastCons30way_mammalian
	-	phastCons17way_primate
	-	SiPhy_29way_logOdds
	-	bStatistic
	-	gnomAD_genomes_AF
	-	gnomAD_genomes_AFR_AF
	-	gnomAD_genomes_AMI_AF
	-	gnomAD_genomes_AMR_AF
	-	gnomAD_genomes_ASJ_AF
	-	gnomAD_genomes_EAS_AF
	-	gnomAD_genomes_FIN_AF
	-	gnomAD_genomes_MID_AF
	-	gnomAD_genomes_NFE_AF
	-	gnomAD_genomes_SAS_AF
	-	aaref_A
	-	aaref_C
	-	aaref_D
	-	aaref_E
	-	aaref_F
	-	aaref_G
	-	aaref_H
	-	aaref_I
	-	aaref_K
	-	aaref_L
	-	aaref_M
	-	aaref_N
	-	aaref_P
	-	aaref_Q
	-	aaref_R
	-	aaref_S
	-	aaref_T
	-	aaref_U
	-	aaref_V
	-	aaref_W
	-	aaref_X
	-	aaref_Y
	-	aaalt_A
	-	aaalt_C
	-	aaalt_D
	-	aaalt_E
	-	aaalt_F
	-	aaalt_G
	-	aaalt_H
	-	aaalt_I
	-	aaalt_K
	-	aaalt_L
	-	aaalt_M
	-	aaalt_N
	-	aaalt_P
	-	aaalt_Q
	-	aaalt_R
	-	aaalt_S
	-	aaalt_T
	-	aaalt_V
	-	aaalt_W
	-	aaalt_X
	-	aaalt_Y

nssnv_median:
 SIFT_score: 0.06199999898672104
 SIFT4G_score: 0.1080000028014183
 Polyphen2_HDIV_score: 0.48500001430511475
 Polyphen2_HVAR_score: 0.16699999570846558
 LRT_score: 0.00011200000153621659
 LRT_Omega: 0.1196729987859726
 MutationTaster_converted_rankscore: 0.8100100159645081
 MutationAssessor_score: 1.6100000143051147
 FATHMM_score: -0.2199999988079071
 PROVEAN_score: -1.5800000429153442
 PROVEAN_converted_rankscore: 0.4390600025653839
 VEST4_score: 0.5450000166893005
 MetaSVM_score: -0.7731999754905701
 MetaLR_score: 0.19979999959468842
 Reliability_index: 10.0
 MetaRNN_score: 0.02568286657333374
 M-CAP_score: 0.08201000094413757
 REVEL_score: 0.21199999749660492
 MutPred_score: 0.5960000157356262
 MVP_score: 0.6482067108154297
 MPC_score: 0.36203378438949585
 PrimateAI_score: 0.5189425349235535
 DEOGEN2_score: 0.1603820025920868
 BayesDel_addAF_score: 0.1817370057106018
 BayesDel_noAF_score: 0.1416580080986023
 ClinPred_score: 0.07361292839050293
 LIST-S2_score: 0.8526149988174438
 CADD_raw: 3.801330089569092
 CADD_phred: 25.799999237060547
 DANN_score: 0.9942993521690369
 fathmm-MKL_coding_score: 0.9268699884414673
 fathmm-XF_coding_score: 0.2985199987888336
 Eigen-raw_coding: 0.4470433294773102
 Eigen-phred_coding: 4.64929723739624
 Eigen-PC-raw_coding: 0.3914338946342468
 Eigen-PC-phred_coding: 4.298270225524902
 GenoCanyon_score: 0.9999961853027344
 integrated_fitCons_score: 0.6717699766159058
 integrated_confidence_value: 0.0
 GM12878_fitCons_score: 0.6159480214118958
 H1-hESC_fitCons_score: 0.6589829921722412
 HUVEC_fitCons_score: 0.6355509757995605
 LINSIGHT: 0.9758660197257996
 GERP++_NR: 5.340000152587891
 GERP++_RS: 4.579999923706055
 phyloP100way_vertebrate: 3.869999885559082
 phyloP30way_mammalian: 1.0260000228881836
 phyloP17way_primate: 0.5989999771118164
 phastCons100way_vertebrate: 1.0
 phastCons30way_mammalian: 0.9879999756813049
 phastCons17way_primate: 0.9629999995231628
 SiPhy_29way_logOdds: 13.411700248718262
 bStatistic: 707.0
 gnomAD_genomes_AF: 0.0005719619803130627
 gnomAD_genomes_AFR_AF: 0.00024128900258801877
 gnomAD_genomes_AMI_AF: 0.0
 gnomAD_genomes_AMR_AF: 0.0002617459977045655
 gnomAD_genomes_ASJ_AF: 0.0
 gnomAD_genomes_EAS_AF: 0.0
 gnomAD_genomes_FIN_AF: 0.0
 gnomAD_genomes_MID_AF: 0.0
 gnomAD_genomes_NFE_AF: 5.6453049182891846e-05
 gnomAD_genomes_SAS_AF: 0.0
