 raw_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - coding
 - aloft.affect
 - aloft.tolerant
 - aloft.recessive
 - aloft.dominant
 - aloft.pred
 - aloft.conf
 - cadd_exome.phred
 - cgd.inheritance
 - chasmplus.score
 - chasmplus.pval
 - civic.clinical_a_score
 - cosmic.variant_count
 - cosmic_gene.occurrences
 - cscape.score
 - cgc.class
 - cgc.inheritance
 - cancer_genome_interpreter.resistant
 - cancer_genome_interpreter.responsive
 - cancer_genome_interpreter.other
 - ccre_screen._group
 - ccre_screen.bound
 - clingen.disease
 - clingen.classification
 - clinpred.score
 - clinvar.sig
 - clinvar.id
 - clinvar.rev_stat
 - clinvar.sig_conf
 - dann.score
 - dann_coding.dann_coding_score
 - dgi.interaction
 - dgi.score
 - ensembl_regulatory_build.region
 - ess_gene.indispensability_score
 - exac_gene.exac_pli
 - exac_gene.exac_pnull
 - exac_gene.exac_del_score
 - exac_gene.exac_dup_score
 - exac_gene.exac_cnv_score
 - exac_gene.exac_cnv_flag
 - fathmm.fathmm_score
 - fathmm_xf_coding.fathmm_xf_coding_score
 - funseq2.score
 - gerp.gerp_rs
 - ghis.ghis
 - gtex.gtex_tissue
 - gwas_catalog.pval
 - genehancer.feature_name
 - genehancer.score
 - linsight.value
 - lrt.lrt_score
 - lrt.lrt_omega
 - loftool.loftool_score
 - mitomap.score
 - mitomap.status
 - mavedb.score
 - metalr.score
 - metasvm.score
 - mutpred1.mutpred_general_score
 - mutpred_indel.score
 - mutation_assessor.score
 - mutationtaster.score
 - mutationtaster.prediction
 - mutationtaster.model
 - ncbigene.entrez
 - ndex_chd.numhit
 - ndex_chd.numhit
 - ndex.numhit
 - ndex_signor.numhit
 - ndex_signor.numhit
 - omim.omim_id
 - prec.prec
 - prec.stat
 - provean.score
 - pangalodb.sensitivity
 - pangalodb.specificity
 - phdsnpg.score
 - phastcons.phastcons100_vert
 - phastcons.phastcons30_mamm
 - phastcons.phastcons17way_primate
 - phylop.phylop100_vert
 - phylop.phylop30_mamm
 - phylop.phylop17_primate
 - polyphen2.hdiv_rank
 - polyphen2.hvar_rank
 - revel.score
 - rvis.rvis_evs
 - repeat.repeatclass
 - sift.score
 - sift.med
 - sift.confidence
 - sift.seqs
 - segway.mean_score
 - siphy.logodds_rank
 - spliceai.ds_ag
 - spliceai.ds_al
 - spliceai.ds_dg
 - spliceai.ds_dl
 - spliceai.dp_ag
 - spliceai.dp_al
 - spliceai.dp_dg
 - spliceai.dp_dl
 - uniprot.acc
 - vest.score
 - dbsnp.rsid
 - dbscsnv.ada_score
 - dbscsnv.rf_score
 - gnomad.af
 - gnomad_gene.oe_lof
 - gnomad_gene.oe_mis
 - gnomad_gene.oe_syn
 - gnomad_gene.lof_z
 - gnomad_gene.mis_z
 - gnomad_gene.syn_z
 - gnomad_gene.pLI
 - gnomad_gene.pRec
 - gnomad_gene.pNull
 - gnomad3.af
 - phi.phi
