raw_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - DExTR_Adipose_Tissue
 - DExTR_Muscle
 - DExTR_Blood_Vessel
 - DExTR_Heart
 - DExTR_Uterus
 - DExTR_Vagina
 - DExTR_Breast
 - DExTR_Skin
 - DExTR_Salivary_Gland
 - DExTR_Brain
 - DExTR_Adrenal_Gland
 - DExTR_Thyroid
 - DExTR_Lung
 - DExTR_Spleen
 - DExTR_Pancreas
 - DExTR_Esophagus
 - DExTR_Stomach
 - DExTR_Colon
 - DExTR_Small_Intestine
 - DExTR_Prostate
 - DExTR_Testis
 - DExTR_Nerve
 - DExTR_Blood
 - DExTR_Pituitary
 - DExTR_Ovary
 - DExTR_Liver
 - DExTR_Kidney
 - DExTR_Cervix_Uteri
 - DExTR_Fallopian_Tube
 - DExTR_Bladder
 - chrom
 - pos
 - ref_base
 - alt_base
 - coding
 - aloft.affect
 - aloft.tolerant
 - aloft.recessive
 - aloft.dominant
 - aloft.pred
 - aloft.conf
 - cadd_exome.phred
 - cgd.inheritance
 - chasmplus.score
 - chasmplus.pval
 - civic.clinical_a_score
 - cosmic.variant_count
 - cosmic_gene.occurrences
 - cscape.score
 - cgc.class
 - cgc.inheritance
 - cancer_genome_interpreter.resistant
 - cancer_genome_interpreter.responsive
 - cancer_genome_interpreter.other
 - ccre_screen._group
 - ccre_screen.bound
 - clingen.disease
 - clingen.classification
 - clinpred.score
 - clinvar.sig
 - clinvar.id
 - clinvar.rev_stat
 - clinvar.sig_conf
 - dann.score
 - dann_coding.dann_coding_score
 - dgi.interaction
 - dgi.score
 - ensembl_regulatory_build.region
 - ess_gene.indispensability_score
 - exac_gene.exac_pli
 - exac_gene.exac_pnull
 - exac_gene.exac_del_score
 - exac_gene.exac_dup_score
 - exac_gene.exac_cnv_score
 - exac_gene.exac_cnv_flag
 - fathmm.fathmm_score
 - fathmm_xf_coding.fathmm_xf_coding_score
 - funseq2.score
 - gerp.gerp_rs
 - ghis.ghis
 - gtex.gtex_tissue
 - gwas_catalog.pval
 - genehancer.feature_name
 - genehancer.score
 - linsight.value
 - lrt.lrt_score
 - lrt.lrt_omega
 - loftool.loftool_score
 - mavedb.score
 - metalr.score
 - metasvm.score
 - mutpred1.mutpred_general_score
 - mutpred_indel.score
 - mutation_assessor.score
 - mutationtaster.score
 - mutationtaster.prediction
 - mutationtaster.model
 - ncbigene.entrez
 - ndex_chd.numhit
 - ndex.numhit
 - ndex_signor.numhit
 - omim.omim_id
 - prec.prec
 - prec.stat
 - provean.score
 - pangalodb.sensitivity
 - pangalodb.specificity
 - phdsnpg.score
 - phastcons.phastcons100_vert
 - phastcons.phastcons30_mamm
 - phastcons.phastcons17way_primate
 - phylop.phylop100_vert
 - phylop.phylop30_mamm
 - phylop.phylop17_primate
 - polyphen2.hdiv_rank
 - polyphen2.hvar_rank
 - revel.score
 - rvis.rvis_evs
 - repeat.repeatclass
 - sift.score
 - sift.med
 - sift.confidence
 - sift.seqs
 - segway.mean_score
 - siphy.logodds_rank
 - spliceai.ds_ag
 - spliceai.ds_al
 - spliceai.ds_dg
 - spliceai.ds_dl
 - spliceai.dp_ag
 - spliceai.dp_al
 - spliceai.dp_dg
 - spliceai.dp_dl
 - uniprot.acc
 - vest.score
 - dbsnp.rsid
 - dbscsnv.ada_score
 - dbscsnv.rf_score
 - gnomad.af
 - gnomad_gene.oe_lof
 - gnomad_gene.oe_mis
 - gnomad_gene.oe_syn
 - gnomad_gene.lof_z
 - gnomad_gene.mis_z
 - gnomad_gene.syn_z
 - gnomad_gene.pLI
 - gnomad_gene.pRec
 - gnomad_gene.pNull
 - gnomad3.af
 - phi.phi

display_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - coding
 - cadd_exome.phred
 - clingen.disease
 - clingen.classification
 - clinvar.sig
 - clinvar.id
 - clinvar.rev_stat
 - clinvar.sig_conf
 - ncbigene.entrez
 - omim.omim_id
 - uniprot.acc
 - dbsnp.rsid

id_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - clingen.disease
 - clingen.classification
 - clinvar.id
 - clinvar.sig
 - clinvar.rev_stat
 - clinvar.sig_conf
 - ncbigene.entrez
 - omim.omim_id
 - uniprot.acc
 - dbsnp.rsid

train_ClinicalSignificance:
 - Uncertain significance
 - Pathogenic
 - Likely pathogenic
 - Benign
 - Likely benign
 - Benign/Likely benign
 - Pathogenic/Likely pathogenic
 - Conflicting interpretations of pathogenicity

BenchmarkSignificance:
 - Pathogenic
 - Likely pathogenic
 - Likely benign
 - Benign
 - Benign/Likely benign
 - Pathogenic/Likely pathogenic
 - Pathogenic, other
 - Pathogenic/Likely pathogenic, other
 - Pathogenic, drug response

CLNREVSTAT: #https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/
  -  practice guideline
  -  reviewed by expert panel
  -  criteria provided, multiple submitters, no conflicts
  #-  criteria_provided,_single_submitter

dummies_sep:
 gtex.gtex_tissue: '|'
 dgi.interaction: ','
 cgd.inheritance: '/'
 so: ','
 repeat.repeatclass: ','
 genehancer.feature_name: '/'
 cgc.inheritance: '/'
 cgc.class: ', '

median_scores:
 DExTR_Adipose_Tissue: -62.39960214
 DExTR_Muscle: -157.90062959999997
 DExTR_Blood_Vessel: -56.66313844
 DExTR_Heart: -192.11897009999998
 DExTR_Uterus: -21.69915294
 DExTR_Vagina: -69.25323533
 DExTR_Breast: -41.97212607
 DExTR_Skin: -20.53916321
 DExTR_Salivary_Gland: -76.7753792
 DExTR_Brain: -118.90540929999999
 DExTR_Adrenal_Gland: -79.11240112
 DExTR_Thyroid: -32.05163631
 DExTR_Lung: -39.878867799999995
 DExTR_Spleen: -67.96118139
 DExTR_Pancreas: -336.1687172
 DExTR_Esophagus: -56.00437118
 DExTR_Stomach: -193.8704183
 DExTR_Colon: -39.6943693
 DExTR_Small_Intestine: -42.27475377
 DExTR_Prostate: -54.4245231
 DExTR_Testis: -9.456228797
 DExTR_Nerve: -23.7263633
 DExTR_Blood: -181.1995209
 DExTR_Pituitary: -39.14241921
 DExTR_Ovary: -35.90099484
 DExTR_Liver: -289.111887
 DExTR_Kidney: -127.5745548
 DExTR_Cervix_Uteri: -24.99423209
 DExTR_Fallopian_Tube: 0.0
 DExTR_Bladder: -38.70179792
 aloft.tolerant: 0.0254
 aloft.recessive: 0.5171749999999999
 aloft.dominant: 0.42410000000000003
 cadd_exome.phred: 9.894
 chasmplus.score: 0.071
 chasmplus.pval: 0.285
 civic.clinical_a_score: 4.0
 cosmic.variant_count: 1.0
 cosmic_gene.occurrences: 1573.0
 cscape.score: 0.4793455
 cancer_genome_interpreter.resistant: 0.0
 cancer_genome_interpreter.responsive: 1.0
 cancer_genome_interpreter.other: 0.0
 clinpred.score: 0.08900000000000001
 dann.score: 0.6545129348446139
 dann_coding.dann_coding_score: 0.9943269294611523
 dgi.score: 3.44
 ess_gene.indispensability_score: 0.876052271195032
 exac_gene.exac_pli: 0.00725253971720532
 exac_gene.exac_pnull: 2.54721516269318e-05
 exac_gene.exac_del_score: 0.22288602511090902
 exac_gene.exac_dup_score: 0.15982937633893599
 exac_gene.exac_cnv_score: -0.0430275954791392
 fathmm.fathmm_score: -1.51
 fathmm_xf_coding.fathmm_xf_coding_score: 0.355259
 funseq2.score: 0.7056330706663941
 gerp.gerp_rs: 4.65
 ghis.ghis: 0.5510271529999999
 gwas_catalog.pval: 3e-11
 genehancer.score: 1.09
 linsight.value: 0.1381115
 lrt.lrt_score: 4.9e-05
 lrt.lrt_omega: 0.10129
 loftool.loftool_score: 0.11599999999999999
 mavedb.score: 0.915390540437152
 metalr.score: 0.3835
 metasvm.score: -0.3796
 mutpred1.mutpred_general_score: 0.81
 mutpred_indel.score: 0.578
 mutation_assessor.score: 2.0
 mutationtaster.score: 1.0
 ndex_chd.numhit: 2.0
 ndex.numhit: 4.0
 ndex_signor.numhit: 1.0
 prec.prec: 0.34375
 provean.score: -2.27
 pangalodb.sensitivity: 0.0
 pangalodb.specificity: 0.0112782
 phdsnpg.score: 0.9209999999999999
 phastcons.phastcons100_vert: 1.0
 phastcons.phastcons30_mamm: 0.985
 phastcons.phastcons17way_primate: 0.956
 phylop.phylop100_vert: 4.146
 phylop.phylop30_mamm: 1.026
 phylop.phylop17_primate: 0.599
 polyphen2.hdiv_rank: 0.5543100000000001
 polyphen2.hvar_rank: 0.53214
 revel.score: 0.40399999999999997
 rvis.rvis_evs: -0.34
 sift.score: 1.0
 sift.med: 2.74
 sift.seqs: 46.0
 segway.mean_score: 0.0901259894737
 siphy.logodds_rank: 0.6200100000000001
 spliceai.ds_ag: 0.0004
 spliceai.ds_al: 0.0
 spliceai.ds_dg: 0.0004
 spliceai.ds_dl: 0.0
 spliceai.dp_ag: 0.0
 spliceai.dp_al: 0.0
 spliceai.dp_dg: 0.0
 spliceai.dp_dl: 0.0
 vest.score: 0.74
 dbscsnv.ada_score: 0.9810062561035401
 dbscsnv.rf_score: 0.708
 gnomad.af: 0.000204403902111
 gnomad_gene.oe_lof: 0.3552
 gnomad_gene.oe_mis: 0.88869
 gnomad_gene.oe_syn: 1.0122
 gnomad_gene.lof_z: 3.7411
 gnomad_gene.mis_z: 0.90404
 gnomad_gene.syn_z: -0.1255
 gnomad_gene.pLI: 5.0777e-05
 gnomad_gene.pRec: 0.30551
 gnomad_gene.pNull: 1.4285e-05
 gnomad3.af: 0.000293325
 phi.phi: 0.42565

consequence_cols:
 - 2kb_downstream_variant
 - 2kb_upstream_variant
 - 3_prime_UTR_variant
 - 5_prime_UTR_variant
 - NMD_transcript_variant
 - NSD_transcript
 - complex_substitution
 - exon_loss_variant
 - frameshift_elongation
 - frameshift_truncation
 - inframe_deletion
 - inframe_insertion
 - intron_variant
 - lnc_RNA
 - miRNA
 - misc_RNA
 - missense_variant
 - polymorphic_pseudogene
 - processed_transcript
 - rRNA
 - ribozyme
 - scaRNA
 - snRNA
 - snoRNA
 - splice_site_variant
 - start_lost
 - start_retained_variant
 - stop_gained
 - stop_lost
 - stop_retained_variant
 - synonymous_variant
 - transcript_ablation

filtered_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - clingen.disease
 - clingen.classification
 - clinvar.id
 - clinvar.rev_stat
 - clinvar.sig_conf
 - ncbigene.entrez
 - omim.omim_id
 - uniprot.acc
 - dbsnp.rsid
 - DExTR_Adipose_Tissue
 - DExTR_Muscle
 - DExTR_Blood_Vessel
 - DExTR_Heart
 - DExTR_Uterus
 - DExTR_Vagina
 - DExTR_Breast
 - DExTR_Skin
 - DExTR_Salivary_Gland
 - DExTR_Brain
 - DExTR_Adrenal_Gland
 - DExTR_Thyroid
 - DExTR_Lung
 - DExTR_Spleen
 - DExTR_Pancreas
 - DExTR_Esophagus
 - DExTR_Stomach
 - DExTR_Colon
 - DExTR_Small_Intestine
 - DExTR_Prostate
 - DExTR_Testis
 - DExTR_Nerve
 - DExTR_Blood
 - DExTR_Pituitary
 - DExTR_Ovary
 - DExTR_Liver
 - DExTR_Kidney
 - DExTR_Cervix_Uteri
 - DExTR_Fallopian_Tube
 - DExTR_Bladder
 - aloft.tolerant
 - aloft.recessive
 - aloft.dominant
 - cadd_exome.phred
 - chasmplus.score
 - chasmplus.pval
 - civic.clinical_a_score
 - cosmic.variant_count
 - cosmic_gene.occurrences
 - cscape.score
 - cancer_genome_interpreter.resistant
 - cancer_genome_interpreter.responsive
 - cancer_genome_interpreter.other
 - clinpred.score
 - dann.score
 - dann_coding.dann_coding_score
 - dgi.score
 - ess_gene.indispensability_score
 - exac_gene.exac_pli
 - exac_gene.exac_pnull
 - exac_gene.exac_del_score
 - exac_gene.exac_dup_score
 - exac_gene.exac_cnv_score
 - fathmm.fathmm_score
 - fathmm_xf_coding.fathmm_xf_coding_score
 - funseq2.score
 - gerp.gerp_rs
 - ghis.ghis
 - gwas_catalog.pval
 - genehancer.score
 - linsight.value
 - lrt.lrt_score
 - lrt.lrt_omega
 - loftool.loftool_score
 - mavedb.score
 - metalr.score
 - metasvm.score
 - mutpred1.mutpred_general_score
 - mutpred_indel.score
 - mutation_assessor.score
 - mutationtaster.score
 - ndex_chd.numhit
 - ndex.numhit
 - ndex_signor.numhit
 - prec.prec
 - provean.score
 - pangalodb.sensitivity
 - pangalodb.specificity
 - phdsnpg.score
 - phastcons.phastcons100_vert
 - phastcons.phastcons30_mamm
 - phastcons.phastcons17way_primate
 - phylop.phylop100_vert
 - phylop.phylop30_mamm
 - phylop.phylop17_primate
 - polyphen2.hdiv_rank
 - polyphen2.hvar_rank
 - revel.score
 - rvis.rvis_evs
 - sift.score
 - sift.med
 - sift.seqs
 - segway.mean_score
 - siphy.logodds_rank
 - spliceai.ds_ag
 - spliceai.ds_al
 - spliceai.ds_dg
 - spliceai.ds_dl
 - spliceai.dp_ag
 - spliceai.dp_al
 - spliceai.dp_dg
 - spliceai.dp_dl
 - vest.score
 - dbscsnv.ada_score
 - dbscsnv.rf_score
 - gnomad.af
 - gnomad_gene.oe_lof
 - gnomad_gene.oe_mis
 - gnomad_gene.oe_syn
 - gnomad_gene.lof_z
 - gnomad_gene.mis_z
 - gnomad_gene.syn_z
 - gnomad_gene.pLI
 - gnomad_gene.pRec
 - gnomad_gene.pNull
 - gnomad3.af
 - phi.phi
 - Adipose_Subcutaneous
 - Adipose_Visceral_Omentum
 - Adrenal_Gland
 - Artery_Aorta
 - Artery_Coronary
 - Artery_Tibial
 - Brain_Amygdala
 - Brain_Anterior_cingulate_cortex_BA24
 - Brain_Caudate_basal_ganglia
 - Brain_Cerebellar_Hemisphere
 - Brain_Cerebellum
 - Brain_Cortex
 - Brain_Frontal_Cortex_BA9
 - Brain_Hippocampus
 - Brain_Hypothalamus
 - Brain_Nucleus_accumbens_basal_ganglia
 - Brain_Putamen_basal_ganglia
 - Brain_Spinal_cord_cervical_c-1
 - Brain_Substantia_nigra
 - Breast_Mammary_Tissue
 - Cells_EBV-transformed_lymphocytes
 - Cells_Transformed_fibroblasts
 - Colon_Sigmoid
 - Colon_Transverse
 - Esophagus_Gastroesophageal_Junction
 - Esophagus_Mucosa
 - Esophagus_Muscularis
 - Heart_Atrial_Appendage
 - Heart_Left_Ventricle
 - Liver
 - Lung
 - Minor_Salivary_Gland
 - Muscle_Skeletal
 - Nerve_Tibial
 - Ovary
 - Pancreas
 - Pituitary
 - Prostate
 - Skin_Not_Sun_Exposed_Suprapubic
 - Skin_Sun_Exposed_Lower_leg
 - Small_Intestine_Terminal_Ileum
 - Spleen
 - Stomach
 - Testis
 - Thyroid
 - Uterus
 - Vagina
 - Whole_Blood
 - activator
 - adduct
 - agonist
 - allosteric modulator
 - antagonist
 - antibody
 - binder
 - blocker
 - chaperone
 - cofactor
 - inducer
 - inhibitor
 - ligand
 - modulator
 - negative modulator
 - positive modulator
 - potentiator
 - product of
 - stimulator
 - substrate
 - vaccine
 - AD
 - AR
 - AR
 - BG
 - Digenic
 - XL
 - 2kb_downstream_variant
 - 2kb_upstream_variant
 - 3_prime_UTR_variant
 - 5_prime_UTR_variant
 - NMD_transcript_variant
 - NSD_transcript
 - complex_substitution
 - exon_loss_variant
 - frameshift_elongation
 - frameshift_truncation
 - inframe_deletion
 - inframe_insertion
 - intron_variant
 - lnc_RNA
 - miRNA
 - misc_RNA
 - missense_variant
 - polymorphic_pseudogene
 - processed_transcript
 - rRNA
 - ribozyme
 - scaRNA
 - snRNA
 - snoRNA
 - splice_site_variant
 - start_lost
 - start_retained_variant
 - stop_gained
 - stop_lost
 - stop_retained_variant
 - synonymous_variant
 - transcript_ablation
 - LINE
 - LTR
 - Low_complexity
 - SINE
 - Satellite
 - Simple_repeat
 - Enhancer
 - Promoter
 - germline
 - somatic
 - Oncogene
 - TSG
 - fusion
 - coding_Yes
 - aloft.affect_all
 - aloft.affect_some
 - aloft.pred_Dominant
 - aloft.pred_Recessive
 - aloft.pred_Tolerant
 - aloft.conf_High Confidence
 - aloft.conf_Low Confidence
 - ccre_screen._group_CTCF-only
 - ccre_screen._group_DNase-H3K4me3
 - ccre_screen._group_PLS
 - ccre_screen._group_dELS
 - ccre_screen._group_pELS
 - ccre_screen.bound_Yes
 - clinvar.sig_Benign
 - clinvar.sig_Benign/Likely benign
 - clinvar.sig_Likely benign
 - clinvar.sig_Likely pathogenic
 - clinvar.sig_Pathogenic
 - clinvar.sig_Pathogenic/Likely pathogenic
 - ensembl_regulatory_build.region_CTCF_binding_site
 - ensembl_regulatory_build.region_TF_binding_site
 - ensembl_regulatory_build.region_enhancer
 - ensembl_regulatory_build.region_open_chromatin_region
 - ensembl_regulatory_build.region_promoter
 - ensembl_regulatory_build.region_promoter_flanking_region
 - exac_gene.exac_cnv_flag_N
 - exac_gene.exac_cnv_flag_Y
 - mutationtaster.prediction_Automatic Disease Causing
 - mutationtaster.prediction_Automatic Polymorphism
 - mutationtaster.prediction_Damaging
 - mutationtaster.prediction_Polymorphism
 - mutationtaster.model_complex_aae
 - mutationtaster.model_simple_aae
 - mutationtaster.model_without_aae
 - prec.stat_lof-tolerant
 - prec.stat_recessive
 - sift.confidence_High
 - sift.confidence_Low
