# columns to be needed in dataset
columns:
  -  Reference Allele
  -  Alternate Allele
  -  Consequence
  -  IMPACT
  -  SYMBOL
  -  Feature
  -  BIOTYPE
  -  SIFT
  -  PolyPhen
  -  CADD_PHRED
  -  CADD_RAW
  -  DANN_score
  -  Eigen-PC-phred_coding
  -  Eigen-PC-raw_coding
  -  Eigen-PC-raw_coding_rankscore
  -  Eigen-phred_coding
  -  Eigen-raw_coding
  -  Eigen-raw_coding_rankscore
  #-  FATHMM_score
  -  GERP++_RS
  -  GenoCanyon_score
  -  LRT_score
  -  M-CAP_score
  -  MetaLR_score
  -  MetaSVM_score
  #-  MutationAssessor_score
  #-  MutationTaster_score
  #-  PROVEAN_score
  -  SiPhy_29way_logOdds
  #-  VEST4_score
  -  fathmm-MKL_coding_score
  -  integrated_fitCons_score
  -  phastCons100way_vertebrate
  -  phastCons30way_mammalian
  -  phyloP100way_vertebrate
  -  phyloP30way_mammalian
  #-  GERP
  -  gnomADv3_AF
  -  gnomADv3_AF_afr
  -  gnomADv3_AF_afr_female
  -  gnomADv3_AF_afr_male
  -  gnomADv3_AF_ami
  -  gnomADv3_AF_ami_female
  -  gnomADv3_AF_ami_male
  -  gnomADv3_AF_amr
  -  gnomADv3_AF_amr_female
  -  gnomADv3_AF_amr_male
  -  gnomADv3_AF_asj
  -  gnomADv3_AF_asj_female
  -  gnomADv3_AF_asj_male
  -  gnomADv3_AF_eas
  -  gnomADv3_AF_eas_female
  -  gnomADv3_AF_eas_male
  -  gnomADv3_AF_female
  -  gnomADv3_AF_fin
  -  gnomADv3_AF_fin_female
  -  gnomADv3_AF_fin_male
  -  gnomADv3_AF_male
  -  gnomADv3_AF_nfe
  -  gnomADv3_AF_nfe_female
  -  gnomADv3_AF_nfe_male
  -  gnomADv3_AF_oth
  -  gnomADv3_AF_oth_female
  -  gnomADv3_AF_oth_male
  -  gnomADv3_AF_raw
  -  gnomADv3_AF_sas
  -  gnomADv3_AF_sas_female
  -  gnomADv3_AF_sas_male
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  hgmd_class
  
ClinicalSignificance:
  -  DP
  -  DFP
  -  FP
  -  DM?
  -  DM
  -  Benign
  -  Benign/Likely_benign
  -  Pathogenic/Likely_pathogenic
  -  Pathogenic
  -  Likely_pathogenic
  -  Likely_benign

Clin_snv:
  -  DP
  -  DFP
  -  FP
  -  DM?
  -  DM
  -  Benign
  -  Benign/Likely_benign
  #-  Pathogenic/Likely_pathogenic
  -  Pathogenic
  -  Likely_pathogenic
  #-  Likely_benign

Clin_non_snv:
  -  DP
  -  DFP
  -  FP
  -  DM?
  -  DM
  -  Benign
  -  Benign/Likely_benign
  #-  Pathogenic/Likely_pathogenic
  -  Pathogenic
  -  Likely_pathogenic
  #-  Likely_benign


CLNREVSTAT:
  -  criteria_provided
  -  _multiple_submitters
  -  _no_conflicts
  -  criteria_provided
  -  _single_submitter 

col_conv:
  -  FATHMM_score
  -  MutationAssessor_score
  -  PROVEAN_score
  -  VEST4_score
  -  GERP
  -  MutationTaster_score

ML_VAR:
  -  SYMBOL
  -  Feature
  -  Consequence
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  Alternate Allele
  -  Reference Allele
  -  ID

var:
  -  SYMBOL
  -  Feature
  -  Consequence
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  Alternate Allele
  -  Reference Allele

Consequence:
  -  missense_variant
  #-  synonymous_variant
  #-  intron_variant
  #-  stop_gained