name: Ditto

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8.5
  - pandas=1.2.1
  - numpy=1.19.5
  - optuna=2.4.0
  - scikit-learn=0.24.1
  - imbalanced-learn=0.7.0
  - scipy=1.6.0
  - shap=0.37.0
  - pip
  - gpy=1.9.9
  - scikit-allel=1.3.2
  - pip:
    - ray==1.1.0
    - ray[tune]
    - tensorflow-gpu==2.4.1
