name: training

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8.5
  - pandas=1.2.1
  #- numpy=1.18.5
  - optuna=2.5.0
  - scikit-learn=0.24.1
  - imbalanced-learn=0.7.0
  #- scipy=1.4.1
  - shap=0.37.0
  - pip
  - gpy=1.9.9
  #- cudatoolkit=11.0.221
  - pip:
    - ray==1.2.0
    - ray[tune]
    - tune-sklearn==0.2.1
    - hyperopt==0.2.5
    - tensorflow-gpu==2.3
    - lz4==3.1.3
