name: rapids

channels:
  - conda-forge
  - nvidia
  - rapidsai
  - defaults

dependencies:
  - python=3.7
  - shap=0.37.0
  - pip
  - cudatoolkit==11.0.221
  - rapids-blazing==0.18
  - pip:
    - ray==1.1.0
    - ray[tune]